name = 'Do What The Fuck You Want To Public License'

description = 'It gives you zero protection. Users can do whatever they want, even sue you. Ultimate freedom!'

fsf = true
osi = false
gpl_compatible = true
copyleft = false
dynamic_linking = true
static_linking = true
intended_for = 'for fucking everything'

permissions = [
'Commercial use',
'Distribution',
'Modification',
'Private use',
]

license = '''
            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                    Version 2, December 2004

 Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>

 Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.
'''
